# Day 07 — Dataset Summary Report

This notebook explores the basic structure and characteristics of the
Day7 Student Dataset using Python and Pandas.

The analysis includes:
- Inspecting the first and last rows
- Viewing random samples
- Checking the shape of the dataset
- Examining columns and index
- Checking data types
- Generating dataset information
- Generating descriptive statistics
- Identifying missing values
- Making basic observations about the dataset

# 1. Inspecting the first and last rows

In [3]:
import pandas as pd

df=pd.read_csv("/content/Day7_Student_Dataset.csv")

In [10]:
#displays the first 5 rows of the DataFrame by default
df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [12]:
#displays the first 10 rows of the DataFrame
df.head(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow
5,1006,Ishita Gupta,20,Computer Science,88.0,93.0,Bengaluru
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune
7,1008,Sara Ahmed,19,AI,73.0,NaN,Hyderabad
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

In [13]:
#displays the last 5 rows of the DataFrame by default
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [14]:
#displays the last 10 rows of the DataFrame
df.tail(10)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
15,1016,Hiba Sheikh,21,Data Science,94.0,96.0,Srinagar
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
18,1019,Yusuf Dar,20,Data Science,NaN,87.0,Srinagar
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [15]:
#displays any  random row of the DataFrame by default
df.sample()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
6,1007,Aditya Verma,22,Data Science,95.0,97.0,Pune

In [20]:
#displays any 5 random rows of the DataFrame by default
# We use random_state=42?
# Because without it, the randomly selected rows can change every time we execute the cell.
df.sample(5, random_state=42)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
8,1009,Arjun Nair,18,Computer Science,84.0,86.0,Kochi
16,1017,Dev Patel,19,AI,86.0,89.0,Ahmedabad
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi

In [23]:
#now to check the shape
rows,cols=df.shape

print("Number of rows: ",rows)
print("Number of columns: ",cols)

Number of rows:  25
Number of columns:  7

In [25]:
#now to check the columns
df.columns

Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

In [28]:
print("Columns in the dataset:\n")
print()
for column in df.columns:
  print(column)

Columns in the dataset:

Student_ID
Name
Age
Course
Marks
Attendance_Percentage
City

In [29]:
#now to check the index range
df.index

RangeIndex(start=0, stop=25, step=1)

In [31]:
#to check the datatype of each and every columns
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

#2 Descriptive statistics using functions such as info() and describe()

### info()

This will show:

- number of rows\Index range
- column names
- non-null values
- data types
- memory usage

In [32]:
#using info()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

### describe()

This gives descriptive statistics for numerical columns.

This will show:

- count
- mean
- std
- min
- 25%
- 50%
- 75%
- max

In [33]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

# Checking missing vcalues

In [34]:
df.isna()

    Student_ID   Name    Age  Course  Marks  Attendance_Percentage   City
0        False  False  False   False  False                  False  False
1        False  False  False   False  False                  False  False
2        False  False  False   False  False                  False  False
3        False  False  False   False  False                  False  False
4        False  False  False   False  False                  False  False
5        False  False  False   False  False                  False  False
6        False  False  False   False  False                  False  False
7        False  False  False   False  False                   True  False
8        False  False  False   False  False                  False  False
9        False  False  False   False  False                  False  False
10       False  False  False   False  False                  False  False
11       False  False  False   False  False                  False  False
12       False  False  False   False  False                  False  False
13       False  False  False   False  False                  False   True
14       False  False  False   False  False                  False  False
15       False  False  False   False  False                  False  False
16       False  False  False   False  False                  False  False
17       False  False  False   False  False                  False  False
18       False  False  False   False   True                  False  False
19       False  False  False   False  False                  False  False
20       False  False  False   False  False                  False  False
21       False  False  False   False  False                  False  False
22       False  False  False   False  False                  False  False
23       False  False  False   False  False                  False  False
24       False  False  False   False  False                  False  False

In [39]:
print("missing values in every column: \n")
df.isna().sum()

missing values in every column:

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [40]:
print("\n Total missing values in the dataset: \n")
df.isna().sum().sum()

 Total missing values in the dataset:

np.int64(3)

# 3 Observation

After exploring the dataset using Pandas, the following observations were made:

* The dataset contains **25 rows and 7 columns**.
* The available features are `Student_ID`, `Name`, `Age`, `Course`, `Marks`, `Attendance_Percentage`, and `City`.
* The dataset contains both **numerical and categorical/text features**.
* `Student_ID` and `Age` are integer (`int64`) columns.
* `Marks` and `Attendance_Percentage` are floating-point (`float64`) columns.
* `Name`, `Course`, and `City` are text/object (`object`) columns.
* Missing values are present in the dataset and can be identified using `info()` and `isnull().sum()`.
* The `Marks`, `Attendance_Percentage`, and `City` columns contain missing values.
* The `describe()` function provides useful statistics such as count, mean, standard deviation, minimum, quartiles, and maximum for numerical columns.
* The dataset can be considered a small student-information dataset suitable for practicing basic Pandas data inspection techniques.

Overall, this analysis demonstrates how Pandas can be used to quickly understand the structure, data types, dimensions, descriptive statistics, and missing values of a dataset before performing further analysis.