# Day 07 — Pandas Practice Notebook

A beginner-friendly introduction to **Pandas**, a Python library widely used for working with tabular data.

The goal is to understand the two most important Pandas data structures:

- **Series** — a one-dimensional labelled collection of values.
- **DataFrame** — a two-dimensional table made of rows and columns.

Topics:

1. Create Series and DataFrames.
2. Convert between Pandas and NumPy.
3. Perform basic Series operations.
4. Load and save CSV files.
5. Understand useful `read_csv()` parameters.
6. Inspect a dataset using `head()`, `tail()`, `sample()`, `info()`, `columns`, `index`, `dtypes`, and `describe()`.
7. Recognize common problems that can occur while loading data.

> **Note:** This is a practice/learning notebook. The Day 07 assignment should be completed separately.

## 1. What is Pandas?

**Pandas** is a Python library designed for data manipulation and analysis.

A simple way to think about it:

> **NumPy is excellent for numerical arrays, while Pandas adds labels, tables, and many convenient data-analysis operations.**

Pandas is especially useful when working with data stored in formats such as CSV, Excel, SQL tables, and JSON.

In [1]:
import pandas as pd

## 2. Pandas Series

A **Series** is a one-dimensional data structure with:

- values
- an index (labels for the values)

You can think of it as a single column of a table.

### 2.1 Creating a Series from a list

In [2]:
numbers = [1, 2, 3, 4, 5]

s = pd.Series(numbers)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

By default, Pandas creates an integer index starting at `0`.

So the data is conceptually:

| Index | Value |
|---:|---:|
| 0 | 1 |
| 1 | 2 |
| 2 | 3 |
| 3 | 4 |
| 4 | 5 |

### 2.2 Creating a Series with custom index labels

In [3]:
scores = [49, 22, 40, 35, 45]

s = pd.Series(
    scores,
    index=["Python", "SQL", "Pandas", "NumPy", "Statistics"]
)

s

Python        49
SQL           22
Pandas        40
NumPy         35
Statistics    45
dtype: int64

Here, the labels are meaningful names instead of `0, 1, 2, ...`.

This is one of the advantages of Pandas: **values can be accessed using meaningful labels.**

### 2.3 Creating a Series from a dictionary

In [4]:
python_scores = {
    "Olii": 49,
    "Maly": 22,
    "Saurab": 40
}

s = pd.Series(python_scores)
s

Olii      49
Maly      22
Saurab    40
dtype: int64

When a dictionary is passed to `pd.Series()`, its **keys become the index** and its **values become the Series values**.

In [5]:
print("Original dictionary:", python_scores)
print("Type of dictionary:", type(python_scores))
print("Type of Series:", type(s))

Original dictionary: {'Olii': 49, 'Maly': 22, 'Saurab': 40}
Type of dictionary: <class 'dict'>
Type of Series: <class 'pandas.Series'>

## 3. Pandas DataFrame

A **DataFrame** is a two-dimensional labelled table.

It contains:

- **Rows** — individual records.
- **Columns** — features/attributes.
- **Index** — labels used to identify rows.

A DataFrame is similar to a spreadsheet or a database table.

### 3.1 Creating a DataFrame from a dictionary

In [6]:
cars = {
    "name": ["Audi", "BMW", "MG"],
    "rating": [9, 8.5, 6]
}

df = pd.DataFrame(cars)
df

   name  rating
0  Audi     9.0
1   BMW     8.5
2    MG     6.0

Each dictionary key becomes a column.

For example:

- `name` → one column
- `rating` → another column

The lists provide the values for those columns.

### 3.2 Creating a DataFrame from a NumPy array

In [7]:
import numpy as np

array = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

df = pd.DataFrame(array)
df

   0  1
0  1  2
1  3  4
2  5  6

A NumPy array does not contain column names by default, so Pandas creates the default column labels `0` and `1`.

### 3.3 Converting a DataFrame to a NumPy array

In [8]:
numpy_array = df.to_numpy()
numpy_array

array([[1, 2],
       [3, 4],
       [5, 6]])

`to_numpy()` converts the DataFrame's values into a NumPy array.

This is useful when you need to pass the numerical data to code or libraries that expect NumPy arrays.

## 4. Basic Series Operations

Pandas Series support many normal arithmetic operations.

The important idea is that Pandas performs operations while respecting the Series index.

In [9]:
s1 = pd.Series(
    [10, 20, 30],
    index=["a", "b", "c"]
)

print("Original Series:")
print(s1)

print("\nSeries multiplied by 2:")
print(s1 * 2)

Original Series:
a    10
b    20
c    30
dtype: int64

Series multiplied by 2:
a    20
b    40
c    60
dtype: int64

### 4.1 Series operations align by index

In [10]:
s2 = pd.Series(
    [1, 3, 4],
    index=["a", "c", "d"]
)

print("s1:")
print(s1)

print("\ns2:")
print(s2)

print("\ns1 + s2:")
print(s1 + s2)

s1:
a    10
b    20
c    30
dtype: int64

s2:
a    1
c    3
d    4
dtype: int64

s1 + s2:
a    11.0
b     NaN
c    33.0
d     NaN
dtype: float64

Notice that Pandas matches values using their **index labels**:

- `a` exists in both Series → values are added.
- `c` exists in both Series → values are added.
- `b` exists only in `s1` → result is `NaN`.
- `d` exists only in `s2` → result is `NaN`.

This behaviour is called **index alignment**.

## 5. Reading a CSV File

CSV stands for **Comma-Separated Values**.

A CSV file commonly looks like this:

```text
id,name,marks
101,Olii,98
102,Max,60
103,Sai,80
```

Pandas provides `pd.read_csv()` to load CSV data into a DataFrame.

In [11]:
# Example:
# df = pd.read_csv("data.csv")

### Important

The file path must point to the location of your CSV file.

In Google Colab, uploaded files are commonly available under `/content/`.

### Example using a CSV already available in Colab

In [12]:
# Example only — run this when the file exists at this path.

# df = pd.read_csv("/content/sample_data/california_housing_train.csv")
# df.head()

## 6. Viewing the Data

After loading a dataset, do not immediately start analysis.

First, inspect it.

### `head()`

Displays the first few rows.

In [13]:
# df.head()

By default, `head()` displays the first **5 rows**.

We can choose how many rows we want:

In [14]:
# df.head(10)

### `tail()`

In [15]:
# df.tail()

`tail()` displays the last 5 rows by default.

We can also specify a number:

In [16]:
# df.tail(10)

### `sample()`

In [17]:
# df.sample()

`sample()` returns a random row.

To get multiple random rows:

In [18]:
# df.sample(5)

A random sample is useful because it can reveal data values that may not appear in the first or last few rows.

## 7. Saving a DataFrame as CSV

Use `to_csv()` to save a DataFrame as a CSV file.

The argument `index=False` prevents Pandas from writing the DataFrame index as an extra column.

In [19]:
# df.to_csv("output.csv", index=False)

## 8. Important `read_csv()` Parameters

`pd.read_csv()` has many parameters. You do not need to memorize all of them immediately.

### `sep` — specify the separator

In [20]:
# Comma-separated file (default)
# df = pd.read_csv("data.csv", sep=",")

# Tab-separated file
# df = pd.read_csv("data.tsv", sep="\t")

# Semicolon-separated file
# df = pd.read_csv("data.csv", sep=";")

If the file uses something other than a comma to separate columns, use `sep`.

### `header` — identify the header row

In [21]:
# If the first row contains column names (default):
# df = pd.read_csv("data.csv", header=0)

# If the file has no header:
# df = pd.read_csv("data.csv", header=None)

When `header=None` is used, Pandas treats the data as having no column-name row and creates default column labels.

### `names` — provide column names

In [22]:
# Example:
# df = pd.read_csv(
#     "data.csv",
#     header=None,
#     names=["id", "name", "marks"]
# )

Use `names` when you want to provide your own column names, especially when the CSV does not contain a header row.

### `index_col` — use a column as the DataFrame index

In [23]:
# Example:
# df = pd.read_csv("data.csv", index_col="id")

This tells Pandas to use the `id` column as the row index instead of creating the default `0, 1, 2, ...` index.

### `usecols` — load only selected columns

In [24]:
# Example:
# df = pd.read_csv(
#     "data.csv",
#     usecols=["id", "name"]
# )

`usecols` is useful when a dataset contains many columns but you only need a few of them.

## 9. Data Inspection

Once a dataset has been loaded, we need to understand its structure.

These commands are among the most important Pandas tools for a beginner:

| Command | What it tells you |
|---|---|
| `df.head()` | First few rows |
| `df.tail()` | Last few rows |
| `df.sample()` | Random rows |
| `df.shape` | Number of rows and columns |
| `df.columns` | Column names |
| `df.index` | Row index information |
| `df.dtypes` | Data type of each column |
| `df.info()` | Compact structural summary |
| `df.describe()` | Descriptive statistics |

The next sections explain each one.

### 9.1 `shape` — number of rows and columns

In [25]:
# df.shape

The result is a tuple:

```text
(rows, columns)
```

For example, `(100, 7)` means:

- 100 rows
- 7 columns

### 9.2 `columns` — column names

In [26]:
# df.columns

This shows all column labels in the DataFrame.

### 9.3 `index` — row index information

In [27]:
# df.index

For a normal DataFrame, you may see something similar to:

```text
RangeIndex(start=0, stop=100, step=1)
```

This means the index starts at `0`, ends before `100`, and increases by `1`.

### 9.4 `dtypes` — data types

In [28]:
# df.dtypes

Common Pandas data types include:

- `int64` → integer values
- `float64` → decimal values
- `object` → commonly used for text/string data
- `bool` → True/False values
- `datetime64` → date/time values

### 9.5 `info()` — compact dataset summary

In [29]:
# df.info()

`info()` is extremely useful because it combines several pieces of information:

- number of rows
- column names
- number of non-null values
- data types
- approximate memory usage

It is one of the first commands you should run after loading an unfamiliar dataset.

### 9.6 `describe()` — descriptive statistics

In [30]:
# df.describe()

For numerical columns, `describe()` normally provides:

- `count`
- `mean`
- `std`
- `min`
- `25%`
- `50%` (median)
- `75%`
- `max`

For example, if a `Marks` column has a mean of `80`, the average mark is 80.

`describe()` is a quick way to understand the distribution and range of numerical data.

### Describing categorical columns

You can also ask `describe()` to include non-numerical columns:

In [31]:
# df.describe(include="all")

For categorical/text columns, useful statistics can include:

- `count` → number of non-missing values
- `unique` → number of distinct values
- `top` → most frequent value
- `freq` → frequency of the most frequent value

## 10. Checking Missing Values

`info()` can show whether the number of non-null values is smaller than the total number of rows.

You can also check missing values directly:

In [32]:
# df.isna().sum()

`isna()` identifies missing values, and `sum()` counts them column by column.

For example:

```text
Marks       1
City        0
Age         0
```

would mean that one value is missing from `Marks`, while `City` and `Age` have no missing values.

## 11. Common Pitfalls When Loading Data

Loading a file successfully does **not** automatically mean that it was loaded correctly.

Always check the data after loading it.

### Common problems

1. **Wrong separator**
   - The file may use `,`, `;`, or tabs.

2. **Missing values**
   - Some cells may be empty or contain special missing-value markers.

3. **Incorrect header handling**
   - The first row may or may not contain column names.

4. **Wrong index**
   - A column may accidentally be used as the index, or the index may have been written to the CSV.

5. **Unexpected data types**
   - A column that should contain numbers may be read as text because of inconsistent values.

### A good first inspection sequence

After loading a new CSV, a useful first check is:

```python
df.head()
df.tail()
df.sample()
df.shape
df.columns
df.index
df.dtypes
df.info()
df.describe()
df.isna().sum()
```

## 12. Quick Practice Checklist

Before moving on, make sure you can explain:

- What is a Series?
- What is a DataFrame?
- What is an index?
- How do you create a Series?
- How do you create a DataFrame?
- How do you read a CSV file?
- How do you save a DataFrame as CSV?
- What does `shape` return?
- What does `dtypes` show?
- What does `info()` show?
- What does `describe()` show?
- How do you check for missing values?
- Why can `s1 + s2` produce `NaN` values?